#!/bin/bash
# Auto restart your stunnel service.
# This shell script would work well on my macOS 10.12.2.
# By kianva 2017.03.07 23:35
stunnelPid=$(ps aux|grep stunnel|grep -v grep|awk '{print $2}')
if [ -z "$stunnelPid" ]; then
        echo 'stunnel is not running'
else
        sudo kill -9 ${stunnelPid} > /dev/null 2>&1
        if [ $? == 0 ]; then
                echo "stop stunnel pid ${stunnelPid} ok"
        else
                echo "error when stopping stunnel,please check by using ps "
        fi
fi
sudo stunnel
if [ $? == 0 ]; then
        echo 'stunnel start ok'
else
        echo 'something wrong when restart stunnel'
fi
unset stunnelPid
